# Generated by Django 2.2.11 on 2020-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200318_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anotherFieldInTemplate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
